[".config/alacritty/themes"]
type = "git-repo"
url = "https://github.com/alacritty/alacritty-theme.git"
[".config/bat/themes/sublime-zenbones"]
type = "git-repo"
url = "https://github.com/Drew-Daniels/sublime-zenbones.git"
["projects/groovy-language-server"]
type = "git-repo"
url = "https://github.com/GroovyLanguageServer/groovy-language-server.git"
["projects/vscode-gradle"]
type = "git-repo"
url = "https://github.com/microsoft/vscode-gradle.git"
["projects/archives"]
type = "git-repo"
url = "https://github.com/Drew-Daniels/archives.git"
["projects/books"]
type = "git-repo"
url = "https://github.com/Drew-Daniels/books.git"
["projects/friendly-snippets"]
type = "git-repo"
url = "https://github.com/Drew-Daniels/friendly-snippets.git"
["projects/work_notes"]
type = "git-repo"
url = "https://github.com/Drew-Daniels/work_notes.git"
["projects/jg"]
type = "git-repo"
url = "https://codeberg.org/drewdaniels/jg.git"
["projects/dotfiles.wiki"]
type = "git-repo"
url = "https://github.com/Drew-Daniels/dotfiles.wiki.git"
